const districts=['Northside',
'West End',
'Downtown',
'Harbor District',
'Southside',
'East Market',
'Industrial Ward',
'Old Quarter'];

const businesses=[['Corner Restaurant',
18000,
3600,
1450],
['Neighborhood Bar',
26000,
4800,
2100],
['Auto Shop',
22000,
3900,
1750],
['Trucking Company',
62000,
9400,
5100],
['Hotel',
145000,
19800,
12600],
['Real Estate Office',
85000,
14200,
6200],
['Music Venue',
52000,
10600,
5900],
['Market',
14000,
2900,
1050],
['Construction Firm',
93000,
16300,
9200],
['Warehouse Lease',
38000,
7200,
3900],
['Bookshop',
11000,
1800,
800],
['Laundromat',
19000,
3500,
1300],
['Catering Company',
28000,
5100,
2400],
['Marina',
125000,
17400,
11400],
['Event Hall',
68000,
12800,
7400],
['Apartment Block',
185000,
22600,
15100],
['Bakery',
16000,
3200,
1200],
['Taxi Cooperative',
45000,
7600,
4200],
['Furniture Store',
32000,
5400,
2900],
['Logistics Group',
210000,
28600,
18100]];

const first=['Marco',
'Elena',
'Anthony',
'Sofia',
'Benny',
'Rosa',
'Vincent',
'Mara',
'Frankie',
'Lucia',
'Nico',
'Celia',
'Tommaso',
'Ada',
'Carlo',
'Lena',
'Dante',
'Mira',
'Sal',
'Inez',
'Rafael',
'Gia',
'Paul',
'Tessa',
'Jonah',
'Mina',
'Luca',
'Nadia'];

const last=['Moretti',
'Russo',
'Bellini',
'Marino',
'Costa',
'Vescari',
'Romano',
'Greco',
'Ferraro',
'Conti',
'DeLuca',
'Serrano',
'Valenti',
'Caruso',
'Bianchi',
'Rinaldi',
'Santoro',
'Esposito',
'Lombardi',
'Orsini'];

const rivals=['The Bellandi Circle',
'Northline Union',
'Vescari Group'];

const eventTemplates=[
['A familiar face',
'An old friend stops by with a small opportunity. They remember who showed up when it mattered.',
['Hear them out',
'Offer a little help',
'Wish them well']],

['A family request',
'Someone close to you needs support, and the timing is difficult.',
['Make time for them',
'Send money',
'Put it off']],

['A quiet opening',
'A local owner is ready to sell before the next lease comes due.',
['Take a closer look',
'Ask a partner to review it',
'Pass for now']],

['A crew question',
'Two people in your circle have different ideas about who should lead the next project.',
['Trust the steady hand',
'Give the newcomer a chance',
'Handle it yourself']],

['Rumors on the block',
'People have started talking about your growing presence. Your crew wants to know what comes next.',
['Keep a low profile',
'Invest in the neighborhood',
'Let the moment pass']],

['A call from home',
'A relative says your last visit was too short. There is still time to change that.',
['Visit this month',
'Promise next month',
'Explain you are busy']],

['A lawyer’s note',
'Your counsel recommends a quieter month while questions circulate.',
['Take the advice',
'Pay for a fuller review',
'Keep your plans']],

['An unexpected inheritance',
'A distant relative has left you a small sum and a box of letters.',
['Save the money',
'Use it to help family',
'Put it toward a venture']],

['The vacant seat',
'A senior figure is stepping back. Several people are watching how you respond.',
['Support a trusted ally',
'Make your case',
'Avoid the contest']],

['A strained partnership',
'A business partner feels their work has gone unnoticed. The books are sound, but goodwill is not.',
['Recognize their effort',
'Offer a bonus',
'Talk it through']],

['A rival’s invitation',
'An intermediary proposes a conversation between your organization and a rival.',
['Meet on neutral ground',
'Send a representative',
'Decline politely']],

['The school letter',
'A young person in your family has been offered a place at a good school. The cost is real.',
['Fund the place',
'Ask about aid',
'Let them choose']],

['A difficult winter',
'Heating bills and repairs have hit several households on your street. Neighbors are watching.',
['Contribute to relief',
'Help one family',
'Keep to your budget']],

['A new generation',
'A younger relative asks what kind of future you think they should build.',
['Encourage their own path',
'Introduce them to the business',
'Ask them to wait']],

['The books need attention',
'A manager flags a dip in revenue and asks for time to refresh the business.',
['Approve a modest upgrade',
'Replace the manager',
'Review it next quarter']],

['A long memory',
'Someone you once disappointed has an opportunity to return the favor—or offer a fresh start.',
['Apologize plainly',
'Make amends',
'Keep your distance']],

['A health reminder',
'A stretch of late nights is catching up with you. A friend suggests taking the month at a slower pace.',
['Rest and reset',
'Keep your routine',
'Book a checkup']],

['A public celebration',
'The neighborhood association is organizing a summer gathering and asks for your support.',
['Sponsor the event',
'Show up in person',
'Decline this year']],

['A crew member’s milestone',
'A loyal colleague marks a personal milestone and hopes you will remember it.',
['Celebrate together',
'Give a thoughtful gift',
'Send a note']],

['An offer from outside',
'A reputable firm wants to discuss a legitimate partnership with one of your businesses.',
['Open talks',
'Ask your manager to lead',
'Wait for more detail']],

['A tense meeting',
'A conversation with a rival has gone quiet. The next move will shape the tone for months.',
['Suggest a compromise',
'Stand by your position',
'Leave the door open']],

['A family dinner',
'Your relatives have made room for you at the table, though old arguments may surface.',
['Go and listen',
'Bring a peace offering',
'Send regrets']],

['A mentor’s advice',
'A mentor tells you that a name lasts longer when the people around it can thrive.',
['Invest in your people',
'Ask what they mean',
'Thank them and move on']],

['The neighborhood paper',
'A local reporter is writing about the district’s changing fortunes and asks for your perspective.',
['Speak about the community',
'Keep your privacy',
'Refer them to a business partner']],

['A succession conversation',
'An older ally asks what you want the next chapter to look like.',
['Talk openly',
'Name a trusted successor',
'Say it is too early']],

['A seasonal rush',
'A business is busier than expected. Staff ask for help keeping service reliable.',
['Hire and train',
'Offer a short bonus',
'Let the manager decide']],

['A fresh start',
'Someone who left your circle years ago is ready to reconnect.',
['Meet them halfway',
'Ask a mutual friend',
'Keep the past closed']],

['A public honor',
'A civic group wants to recognize your investment in the city. Some people welcome the attention; others do not.',
['Accept graciously',
'Share the credit',
'Decline the spotlight']],

['A rival in transition',
'A rival organization has changed leadership. Their new representative asks for a first meeting.',
['Set a respectful tone',
'Wait and observe',
'Send a trusted lieutenant']],

['A family keepsake',
'A relative offers you an old photograph and tells you the story behind it.',
['Make time for the story',
'Ask about your family history',
'Thank them and return to work']],

['A good year',
'The people around you point out how far the organization has come. They want to mark the moment.',
['Celebrate with the crew',
'Thank people privately',
'Put the money aside']],

['An uneasy question',
'Someone close asks whether your ambition is making it harder to be present.',
['Listen without rushing',
'Explain your priorities',
'Change the subject']],

['A local grant',
'A community group is seeking sponsors for a youth program near one of your businesses.',
['Fund the program',
'Offer space and mentorship',
'Decline this cycle']],

['A careful expansion',
'A neighboring district has room for new investment, but residents want to know your intentions.',
['Start with a local partnership',
'Study the district longer',
'Focus on home']],

['A quiet apology',
'A colleague admits they handled a disagreement poorly and wants to repair trust.',
['Accept the apology',
'Ask for a little time',
'Keep things professional']],

['A changing market',
'A new competitor is drawing customers from one of your businesses.',
['Refresh the offering',
'Improve the service',
'Review the numbers first']],

['A family celebration',
'A birthday or anniversary is approaching, and someone hopes you will be there.',
['Clear the evening',
'Arrange a thoughtful gift',
'Send your congratulations']],

['An old promise',
'You once promised to help someone get a fair chance. They are ready to take you up on it.',
['Keep your word',
'Find another way to help',
'Be honest about the delay']],

['A leadership opening',
'Your organization needs someone to take on more responsibility. Your choice will be noticed.',
['Promote from within',
'Share the responsibility',
'Hold the structure steady']],

['A hard conversation',
'A loved one wants clearer boundaries between family life and work.',
['Agree on a boundary',
'Ask what would help',
'Defend your current rhythm']],

['A business at a crossroads',
'A long-running business can grow with fresh capital or remain steady and familiar.',
['Invest in growth',
'Keep it dependable',
'Consider a sale']],

['A neighborhood dispute',
'Two local groups disagree about a redevelopment plan. Both want you to listen.',
['Bring them together',
'Support the residents',
'Stay neutral']],

['A letter from prison',
'An old associate writes that time away has changed their priorities.',
['Write back',
'Ask a trusted person to visit',
'Let the past rest']],

['A family ambition',
'A relative has a plan of their own and asks for your support, not your approval.',
['Back their independence',
'Offer practical advice',
'Ask them to reconsider']],

['A difficult choice',
'A close ally is under pressure and would value your public support.',
['Stand beside them',
'Help in private',
'Keep some distance']],

['A new manager',
'A strong candidate wants to lead one of your businesses.',
['Give them a chance',
'Ask for references',
'Promote from the existing team']],

['A season of reflection',
'The year is turning. The choices that brought you here are easier to see in hindsight.',
['Write down what matters',
'Call someone you miss',
'Set a new goal']],

['An invitation uptown',
'A civic leader invites you to a dinner where business and public life overlap.',
['Attend and listen',
'Send a representative',
'Decline the invitation']],

['A succession plan',
'More than one person may be ready to carry your name forward. A conversation now could spare pain later.',
['Start the conversation',
'Ask an elder to mediate',
'Wait until next year']],

['A second chance',
'Someone asks for a chance to prove they have grown beyond an old mistake.',
['Offer measured trust',
'Set a small first step',
'Wish them well from afar']]
];

const jobs=[
['Courier arrangement',
600,
5,
'organization'],
['Market stall partnership',
780,
3,
'legitimate'],

['Neighborhood repair contract',
950,
2,
'legitimate'],
['Harbor supply commission',
1300,
7,
'organization'],

['Evening event staffing',
720,
2,
'legitimate'],
['Warehouse inventory review',
1100,
5,
'organization'],

['Restaurant purchasing deal',
850,
2,
'legitimate'],
['Night market brokerage',
970,
6,
'organization'],

['Festival logistics',
1400,
3,
'legitimate'],
['Private club introduction',
1550,
8,
'organization'],

['Auto shop referral',
690,
2,
'legitimate'],
['Construction bid support',
1750,
5,
'legitimate'],

['District mediation fee',
980,
4,
'organization'],
['Music venue booking',
1250,
3,
'legitimate'],

['Trucking route contract',
1600,
5,
'legitimate'],
['Property showing',
1130,
2,
'legitimate'],

['Hotel conference support',
1900,
4,
'legitimate'],
['Union dinner sponsorship',
880,
3,
'legitimate'],

['Community market grant',
760,
1,
'legitimate'],
['Portside introduction',
1340,
7,
'organization'],

['Old Quarter retail lease',
1470,
3,
'legitimate'],
['Crew coordination fee',
1090,
8,
'organization'],

['Local hiring drive',
670,
1,
'legitimate'],
['Independent vendor agreement',
920,
3,
'legitimate'],

['Charity gala planning',
1860,
2,
'legitimate'],
['Entertainment licensing',
1510,
4,
'legitimate'],

['Fleet maintenance agreement',
1670,
3,
'legitimate'],
['Neighborhood investment pitch',
1190,
4,
'legitimate'],

['Merchant association role',
810,
2,
'legitimate'],
['Private negotiation retainer',
1730,
9,
'organization']
];

const relationshipSituations=[
['An overdue visit',
'A relative says it has been too long since you sat down together.'],

['A missed birthday',
'Someone close noticed your absence at an important celebration.'],

['A difficult loan',
'A family member needs help covering an unexpected expense.'],

['A private ambition',
'A younger relative has a plan they are nervous to share.'],

['A quiet apology',
'Someone who hurt you years ago wants to speak plainly.'],

['A dinner invitation',
'An invitation arrives with a note asking you to come early.'],

['A new home',
'A loved one is considering a move across the city.'],

['A proud moment',
'A family member wants you to see what they accomplished.'],

['A strained holiday',
'Old disagreements threaten to spoil a gathering.'],

['A school decision',
'A child in the family needs encouragement about a difficult choice.'],

['A long drive',
'A relative asks for company on a trip outside the city.'],

['A lost photograph',
'A box of family memories turns up during a move.'],

['A changing friendship',
'An old friend wonders whether your lives still fit together.'],

['The new partner',
'Someone close asks you to meet a person important to them.'],

['A hospital visit',
'A family member faces a brief but unsettling illness.'],

['An honest question',
'Someone asks whether you are happy with the life you built.'],

['A difficult truth',
'A relative admits they have been hiding a disappointment.'],

['A wedding invitation',
'An important celebration will bring several old conflicts together.'],

['A new career',
'A sibling asks what you think of a more independent path.'],

['The family table',
'Two relatives ask you to help ease a disagreement.'],

['A long silence',
'A friend has not called since your last argument.'],

['An anniversary',
'Someone wants the day to feel special, even with little money.'],

['A request for space',
'A loved one needs time to think after a hard month.'],

['An old promise',
'A family member remembers a promise you made years ago.'],

['The next chapter',
'A young relative is weighing life in New Carbone City.'],

['A difficult introduction',
'A partner worries your family will judge them.'],

['A shared project',
'A loved one proposes working together on something modest.'],

['An unexpected guest',
'A distant cousin arrives hoping to reconnect.'],

['A letter from afar',
'A friend who moved away writes with mixed news.'],

['A question of trust',
'Someone close is unsure whether you kept a confidence.'],

['A child’s recital',
'A young family member hopes to find you in the audience.'],

['A difficult budget',
'Someone wants to discuss how money affects your relationship.'],

['A quiet weekend',
'A friend offers a simple plan with no work attached.'],

['A family tradition',
'An elder asks you to keep a small tradition alive.'],

['A surprising offer',
'A relative offers help before you have asked for it.'],

['A new boundary',
'A loved one explains what they need from you going forward.'],

['A chance meeting',
'You cross paths with someone you once knew well.'],

['A celebration delayed',
'An important event was postponed and feelings are mixed.'],

['The older generation',
'An elder wants to talk about mistakes and second chances.'],

['A future imagined',
'Someone asks where you hope the family will be in ten years.']
];
